version: '3'

services:
  app:
    image: traefik:1.3-alpine
    command: 
      --accessLogsFile=/log/access.log 
      --defaultEntryPoints=http,https --entryPoints='Name:http Address::80 Redirect.EntryPoint:https' --entryPoints='Name:https Address::443 TLS' 
      --acme --acme.entrypoint=https --acme.OnHostRule --acme.domains=gokit.info --acme.storage=acme.json --acme.email=llitfkitfk@gmail.com
      --web --docker --docker.swarmmode --docker.watch --docker.domain=gokit.info
      --web.metrics.prometheus --web.metrics.prometheus.buckets="0.1,0.3,1.2,5.0"
    restart: always
    labels: 
      - traefik.enable=false
    networks:
      - gateway
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/null:/traefik.toml
      - data-log:/log
    deploy:
      restart_policy:
        condition: on-failure
        delay: 1s
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.role == manager
          - node.hostname == node1
  nginxredirect:
    image: containerize/nginx-redirect
    environment:
      - SERVER_REDIRECT=dash.gokit.info
    networks:
      - gateway
    labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:gokit.info"
    deploy:
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:gokit.info"
      placement:
        constraints:
          - node.role == manager  
  visualizer:
    image: dockersamples/visualizer:stable
    restart: always
    networks:
      - gateway
    labels:
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:viz.gokit.info"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:viz.gokit.info"
      replicas: 2
      placement:
        constraints: 
          - node.role == manager
  whoami:
    image: emilevauge/whoami
    restart: always
    networks:
      - gateway
    deploy:
      replicas: 3
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:whoami.gokit.info"
  dash:
    image: containerize/nginx-proxy
    restart: always
    environment: 
      - SERVER_PROXY_HOST=app
      - SERVER_PROXY_PORT=8080
    networks:
      - gateway
    deploy:
      replicas: 3
      labels:
        - "traefik.port=80"
        - "traefik.frontend.rule=Host:dash.gokit.info"
volumes:
  data-log:
networks:
  gateway: