version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_config:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      # - '-alertmanager.url=http://alertmanager:9093'
    networks:
      - back-tier
    deploy:
      placement:
        constraints:
          - node.hostname == node2
      restart_policy:
        condition: on-failure
        delay: 1s
      update_config:
        parallelism: 2
        delay: 10s
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '-collector.procfs=/host/proc -collector.sysfs=/host/sys -collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    networks:
      - back-tier
  # alertmanager:
  #   image: prom/alertmanager
  #   ports:
  #     - 9093:9093
  #   volumes:
  #     - alertmanager-config:/etc/alertmanager/
  #   networks:
  #     - back-tier
  #     - gateway
  #   command:
  #     - '-config.file=/etc/alertmanager/config.yml'
  #     - '-storage.path=/alertmanager'
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - back-tier
    deploy:
      mode: global
  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - back-tier
      - gateway
    deploy:
      placement:
        constraints:
          - node.hostname == node2
      labels:
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:monitor.gokit.info"
        - "traefik.docker.network=traefik_gateway"
volumes:
  prometheus_config:
  prometheus_data:
  grafana_data:

networks:
  back-tier:
  gateway:
    external:
      name: traefik_gateway