version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-config:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
      # - '-alertmanager.url=http://alertmanager:9093'
    networks:
      - backend
    deploy:
      placement:
        constraints:
          - node.hostname == node2
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: '-collector.procfs=/host/proc -collector.sysfs=/host/sys -collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    networks:
      - backend
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - backend
    deploy:
      mode: global
  grafana:
    image: grafana/grafana
    volumes:
      - grafana-data:/var/lib/grafana
    environment: 
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - backend
      - gateway
    deploy:
      placement:
        constraints:
          - node.hostname == node2
      labels:
        - "traefik.port=3000"
        - "traefik.frontend.rule=Host:monitor.gokit.info"
        - "traefik.docker.network=traefik_gateway"
volumes:
  prometheus-config:
  prometheus-data:
  grafana-data:

networks:
  backend:
  gateway:
    external:
      name: traefik_gateway