version: '3'

services:
  nginx:
    image: nginx
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname == node1
  admin:
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    labels:
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:admin.gokit.info"
      - "traefik.docker.network=traefik_gateway"
    networks:
      - admin
      - gateway
    deploy:
      labels:
        - "traefik.port=9000"
        - "traefik.frontend.rule=Host:admin.gokit.info"
        - "traefik.docker.network=traefik_gateway"
      restart_policy:
        condition: on-failure
        delay: 1s
      update_config:
        parallelism: 2
        delay: 10s
      placement:
        constraints:
          - node.role == manager
          - node.hostname == node1
  nodes:
    image: containerize/docker-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: $HOSTNAME
    networks:
      - admin
    command: -i
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 1s                
volumes:
  data:
networks:
  admin:
  gateway:
    external:
      name: traefik_gateway